
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.anders_raberg.sudoku;

import static org.junit.jupiter.api.Assertions.assertTrue;
//import org.junit.Test;
import org.junit.jupiter.api.Test;
public class SudokuTest {
    @Test
    public void test() {
        assertTrue(true);
    }
}
