/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.anders_raberg.sudoku;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class SudokuTest {
    @Test
    public void test() {
        assertTrue(true);
    }
}
