/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.anders_raberg.junittest;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;

class LibraryTest {
	@ParameterizedTest(name = "{index} ==> the square of {0} is {1}")
	@ArgumentsSource(MyArgumentsProvider.class)
	void testSquares(int n, int n2) {
		assertEquals(n2, Library.square(n));
	}
}
