plugins {
    id 'application'
    id 'idea'
    id("com.diffplug.spotless") version "8.8.0"
    id 'se.anders_raberg.gradle.plugins.propertiesValidation'
}

spotless {
    java {
        eclipse().configFile("/home/anders/java-code-formatter.xml")
    }
}


group = 'se.anders-raberg.proptest'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'se.anders_raberg.proptest.Main'
}

distributions {
    main {
        contents {
            from 'extraprops'
        }
    }
}

propertiesValidation {
    propertiesFiles.from(getLayout().getProjectDirectory().dir("extraprops"))
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.commonsLang
    testImplementation libs.junitJupiterApi
    testImplementation libs.junitJupiterParams
    testRuntimeOnly libs.junitJupiterEngine
    testRuntimeOnly libs.junitPlatformLauncher
}
test {
    useJUnitPlatform()
}


