module se {
   module anders_raberg {
      module idl {
         module hello {
            interface HelloWorld {
               string hello(in string text);
               void stopServer();
            };
         };
      };
   };
};
